### ISSUE TITLE
Beatmods upload for v1.34.2

### ISSUE THREAD

**Issue by bleetube** [JonnyVR1/AdBlocker#1]
Hello, can you upload this to [beatmods](https://beatmods.com/#/mods) again? I've been using your latest release and it still works just fine afaict. I think you can just re-upload it without any changes. I originally discovered this mod by installing it for v1.29 via BSManager which sources everything from beatmods.  Thanks!

**Comment by JonnyVR1** [comment]
Submitted to Beatmods, it's on them to approve it now.

**Comment by JonnyVR1** [comment]
FYI this was approved up until 1.35 - legit don't even know if anyone has figured out how the internal processes of beatmods works, I didn't change any internal code so there is no reason the 1.29 version could not have been validated beforehand....
